(MAINT) Disable ScreenSaverEngine on macOS 10.13 (High Sierra)
puppetlabs/puppetlabs-packer pull request #309
Opened 2018-05-03 20:08 UTC by scotje

I noticed on the vmpooler VMs that ScreenSaverEngine seems to be using
an inordinate amount of CPU time (30-50%) so this change should disable
the login window screen saver entirely since there is no need for a
headless VM to have it running.

I have no idea if this is the best place to add this or not. I tried to build locally (first a 10.12 image since 10.13 is based on that) but I seemed to be missing some settings. :/

2018-05-04 07:47 UTC, jcoconnor approved these changes
Not very familiar with MacOS build but this looks ok

2018-05-04 17:30 UTC, ScottGarman requested changes
Can you also bump the version in vars.json for 10.13 as well?

2018-05-04 17:36 UTC, scotje commented
@ScottGarman Yep, done!

2018-05-08 22:07 UTC, shrug approved these changes
lgtm, although I have not checked that the actual configuration works as expected

2018-05-09 16:02 UTC, ScottGarman commented
Ah, you're in the same boat as me now (Thinkpad Linux user). Maybe @ekinanp can assist with this? If you can just get the build into vSphere I can validate it from there to keep the time investment minimal.

2018-05-09 18:44 UTC, ekinanp commented
Yeah I can look into that now

2018-05-09 21:49 UTC, ekinanp commented
Nevermind, I will do this tomorrow since John has some Windows builds that are queued up. I have a separate PR https://github.com/puppetlabs/ci-job-configs/pull/4457 for adding Mac OS pipelines that should get merged once I've been able to verify the work here.

2018-05-15 22:17 UTC, shrug commented
@ekinanp Any luck?

2018-05-16 08:15 UTC, ekinanp commented
@shrug Thanks for the reminder! I can build it locally but it's been stuck on the vsphere upload. Going to try it again later during the day.

2018-05-22 22:09 UTC, shrug commented
@ScottGarman @ekinanp - have you been able to test this?

2018-05-22 22:50 UTC, shrug commented
Are you building locally on the VPN? Yeah I can see how the vsphere uploads would be painful, the images are not small.

2018-05-23 17:06 UTC, ekinanp commented
Yeah, no luck on the VPN. Just going to build this tomorrow when I'm in the office.

2018-07-17 22:05 UTC, underscorgan commented
@ekinanp any progress here?

2018-07-18 04:02 UTC, ekinanp commented
@underscorgan This should be rebased to take in some of the recent changes we made to the repo. I haven't built this yet because the upload takes an abnormally long amount of time and I'm on the VPN. But it should be pretty easy for someone in the office to build + upload this in the office using all of the new functionality added to the ci-utils gem during the imaging insurgency. Would be nice if someone could do that. I can walk through all the commands they'd need to run.

2018-08-07 22:10 UTC, mwaggett commented
What is the status of this?
@ScottGarman are there still changes you want to see?
@ekinanp have you done the necessary testing for this?

2018-08-15 19:47 UTC, ScottGarman commented
I don't use Apple hardware (I run Linux on a Thinkpad) and can't take action on this. @ekinanp could you drive this to completion, delegating if necessary?

2018-08-16 13:52 UTC, ekinanp commented
Yeah, I'm in the middle of uploading a template right now. It's at 22%. Hopefully by EOD today it will finish.

2018-10-19 12:57 UTC, jcoconnor commented
Is it appropriate for @loopinu to look at this given that he is also doing MacOS 10.14 ?
Would be good to either merge or close this.

2021-09-01 18:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-packer?pullRequest=309) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-packer?pullRequest=309) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-packer?pullRequest=309) it.</sub>

2023-10-10 21:15 UTC, yachub commented
Closing since this project will be archived shortly.

2023-10-10 21:15 UTC, closed without merging